spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # 默认开启了缓存，修改页面，则刷新的时候得不到修改后的页面，改为false
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.javalizi.blog.pojo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql